// This file was generated by counterfeiter
package fakes

import (
	"os/exec"
	"sync"

	"github.com/cloudfoundry-incubator/genclient"
)

type CommandRunner struct {
	RunStub        func(cmd *exec.Cmd) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		cmd *exec.Cmd
	}
	runReturns struct {
		result1 error
	}
}

func (fake *CommandRunner) Run(cmd *exec.Cmd) error {
	fake.runMutex.Lock()
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		cmd *exec.Cmd
	}{cmd})
	fake.runMutex.Unlock()
	if fake.RunStub != nil {
		return fake.RunStub(cmd)
	} else {
		return fake.runReturns.result1
	}
}

func (fake *CommandRunner) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *CommandRunner) RunArgsForCall(i int) *exec.Cmd {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.runArgsForCall[i].cmd
}

func (fake *CommandRunner) RunReturns(result1 error) {
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

var _ genclient.CommandRunnerInterface = new(CommandRunner)
